"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.UnwindPositionsQuery = exports.OpenPositionsQuery = void 0;
var graphql_request_1 = require("graphql-request");
exports.OpenPositionsQuery = (0, graphql_request_1.gql)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  query openPositions($account: ID!, $first: Int, $skip: Int) {\n    account(id: $account) {\n      positions(\n        where: { isLiquidated: false, currentOi_gt: \"0\" }\n        orderBy: createdAtTimestamp\n        orderDirection: desc\n        first: $first\n        skip: $skip\n      ) {\n        id\n        createdAtTimestamp\n        currentOi\n        entryPrice\n        initialCollateral\n        isLiquidated\n        isLong\n        leverage\n        numberOfUniwnds\n        positionId\n        market {\n          feedAddress\n          id\n        }\n      }\n    }\n  }\n"], ["\n  query openPositions($account: ID!, $first: Int, $skip: Int) {\n    account(id: $account) {\n      positions(\n        where: { isLiquidated: false, currentOi_gt: \"0\" }\n        orderBy: createdAtTimestamp\n        orderDirection: desc\n        first: $first\n        skip: $skip\n      ) {\n        id\n        createdAtTimestamp\n        currentOi\n        entryPrice\n        initialCollateral\n        isLiquidated\n        isLong\n        leverage\n        numberOfUniwnds\n        positionId\n        market {\n          feedAddress\n          id\n        }\n      }\n    }\n  }\n"])));
exports.UnwindPositionsQuery = (0, graphql_request_1.gql)(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  query unwinds($account: ID!, $first: Int, $skip: Int) {\n    account(id: $account) {\n      unwinds(\n        orderBy: timestamp\n        orderDirection: desc\n        first: $first\n        skip: $skip\n      ) {\n        collateral\n        currentDebt\n        currentOi\n        fraction\n        fractionOfPosition\n        id\n        isLong\n        mint\n        pnl\n        price\n        size\n        timestamp\n        transferAmount\n        unwindNumber\n        value\n        position {\n          createdAtTimestamp\n          currentOi\n          entryPrice\n          id\n          initialCollateral\n          isLong\n          leverage\n          numberOfUniwnds\n          positionId\n          market {\n            feedAddress\n            id\n          }\n        }\n      }\n    }\n  }\n"], ["\n  query unwinds($account: ID!, $first: Int, $skip: Int) {\n    account(id: $account) {\n      unwinds(\n        orderBy: timestamp\n        orderDirection: desc\n        first: $first\n        skip: $skip\n      ) {\n        collateral\n        currentDebt\n        currentOi\n        fraction\n        fractionOfPosition\n        id\n        isLong\n        mint\n        pnl\n        price\n        size\n        timestamp\n        transferAmount\n        unwindNumber\n        value\n        position {\n          createdAtTimestamp\n          currentOi\n          entryPrice\n          id\n          initialCollateral\n          isLong\n          leverage\n          numberOfUniwnds\n          positionId\n          market {\n            feedAddress\n            id\n          }\n        }\n      }\n    }\n  }\n"])));
var templateObject_1, templateObject_2;
